#!/bin/bash
set -e

# build ho-hyper ctan distrib
# perhaps use l3build one day, but not today

INSTALLDIR=$HOME/texmf

# starting from ho-hyper.zip and ho-hyper.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex 2> /dev/null || echo target directories not present
rm *.pdf *.aux  2> /dev/null  || echo no pdf or aux here
mkdir -p $HOME/texmf/scripts/ho-hyper


#  make target tds structure
mkdir -p doc/latex/ho-hyper
mkdir -p source/latex/ho-hyper
mkdir -p tex/latex/ho-hyper


# unpack
#
tex ho-hyper.ins



# make pdf
rm *.bbl || echo no bbl
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    #    biber ${i/.dtx}
    bibtex ${i/.dtx}
fi
lualatex ${i}
if [ -f ${i/.dtx/.idx} ]; then
    makeindex -s gind.ist ${i/.dtx/.idx}
    lualatex ${i}
fi
done

lualatex ho-hyper
lualatex ho-hyper


# special cases

# fill tds tree
for i in `cat manifest.txt`
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../ho-hyper.tds.zip
zip -r ../ho-hyper.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm -f ho-hyper.zip
zip ho-hyper.zip ho-hyper.tds.zip ho-hyper/\
{README.txt,\
ho-hyper.tex,\
*.pdf,\
*.dtx\
}

mv ho-hyper*.zip ho-hyper

