#!/bin/bash

SOURCE=$PWD
TEXMFHOME=`kpsexpand '$TEXMFHOME'`

# make current versions
#
./mkctan

# install in local tree
#
cd $TEXMFHOME
unzip -o $SOURCE/../oberdiek.tds.zip

# see what broke
#
cd $SOURCE
for i in *test*.tex
do
    echo "===========" $i
case $i in
    askinclude-test24.tex) pdflatex $i ;; # \pdfmatch not emulated yet in luatex
    grfext-test2.tex) pdflatex $i ;; # explicit pdftex option
    atbegshi-test1*) echo skip;; # error even with pdftex TODO
    atbegshi-test2*|embedfile-test2*|embedfile-test4*|epstopdf-test1*|etexcmds-test2*|hyphsubst-test1*|hyphsubst-test2*|iflang-test4*|iflang-test5*|infwarerr-test2*) echo x | luatex $i;; # plain TeX
    bmpsize-test*) echo "" | luatex $i;; # don't use x as filename
    listingsutf8-test2.tex) pdflatex $i;;#  inputenc
    listingsutf8-test3.tex) echo skip;; # empty?
    listingsutf8-test4.tex) echo skip;; #empty?
    listingsutf8-test5.tex) echo skip;; # empty?
   *) echo x | lualatex $i
esac

done



# list of errors from the tests
#
grep '^\!' *test*.log |egrep -v '(Package PACKAGE|Class CLASS) Error'


