#!/bin/bash

# build oberdiek ctan distrib
# perhaps use l3build one day, but not today


# starting from oberdiek.zip and oberdiek.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex
mv oberdiek.pdf oberdiek.pdf-
rm *.pdf
mv oberdiek.pdf- oberdiek.pdf

# unzip oberdiek.tds.zip to generate initial tds structure
unzip ../oberdiek.tds.zip


# unpack
#
tex oberdiek.ins

# make pdf
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    biber ${i/.dtx}
fi
lualatex ${i}
makeindex -s gind.ist ${i/.dtx/.idx}
lualatex ${i}
done


lualatex oberdiek
lualatex oberdiek


# special cases
cp README readme-ctan.txt
rm -f ./tex/latex/oberdiek/foo.sty
rm -f ./doc/latex/oberdiek/test/ifpdf-test1.tex
rm -f ./source/latex/oberdiek/catalogue/ifpdf.xml

# fill tds tree
for i in `find bibtex doc scripts source tex -type f `
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../oberdiek.tds.zip
zip -r ../oberdiek.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm oberdiek.zip
zip oberdiek.zip oberdiek.tds.zip oberdiek/\
{README,\
*.pdf,\
*.dtx\
}


