#!/bin/bash
set -e

# build oberdiek ctan distrib
# perhaps use l3build one day, but not today

INSTALLDIR=$HOME/texmf

# starting from oberdiek.zip and oberdiek.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex 2> /dev/null || echo target directories not present
rm *.pdf *.aux  2> /dev/null  || echo no pdf or aux here
mkdir -p $HOME/texmf/scripts/oberdiek


#  make target tds structure
mkdir -p scripts/oberdiek
mkdir -p doc/latex/oberdiek
mkdir -p source/latex/oberdiek
mkdir -p tex/generic/oberdiek
mkdir -p tex/latex/oberdiek


# unpack
#
tex oberdiek.ins

# Lua need to be here for doc generation must fix this one day
cp \
    luacolor.lua oberdiek.luacolor.lua \
    luacolor-pre065.lua  oberdiek.luacolor-pre065.lua \
    pdftexcmds.lua oberdiek.pdftexcmds.lua \
    magicnum.lua oberdiek.magicnum.lua \
    oberdiek.luatex.lua \
    scripts/oberdiek

cp \
    luacolor.lua oberdiek.luacolor.lua \
    luacolor-pre065.lua  oberdiek.luacolor-pre065.lua \
    pdftexcmds.lua oberdiek.pdftexcmds.lua \
    magicnum.lua oberdiek.magicnum.lua \
    oberdiek.luatex.lua \
    $HOME/texmf/scripts/oberdiek


# make pdf
rm *.bbl || echo no bbl
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    #    biber ${i/.dtx}
    bibtex ${i/.dtx}
fi
lualatex ${i}
if [ -f ${i/.dtx/.idx} ]; then
    makeindex -s gind.ist ${i/.dtx/.idx}
    lualatex ${i}
fi
done

lualatex oberdiek
lualatex oberdiek


# special cases
cp README readme-ctan.txt
rm -f ./tex/latex/oberdiek/foo.sty
rm -f ./doc/latex/oberdiek/test/ifpdf-test1.tex
rm -f ./source/latex/oberdiek/catalogue/ifpdf.xml

# fill tds tree
for i in `find bibtex doc scripts source tex -type f `
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../oberdiek.tds.zip
zip -r ../oberdiek.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm oberdiek.zip
zip oberdiek.zip oberdiek.tds.zip oberdiek/\
{README,\
oberdiek.tex,\
*.pdf,\
*.dtx\
}


