#!/bin/bash
set -e

# build ho-latex ctan distrib
# perhaps use l3build one day, but not today

INSTALLDIR=$HOME/texmf

# starting from ho-latex.zip and ho-latex.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex 2> /dev/null || echo target directories not present
rm *.pdf *.aux  2> /dev/null  || echo no pdf or aux here
mkdir -p $HOME/texmf/scripts/ho-latex


#  make target tds structure
mkdir -p bibtex/bib/ho-latex
mkdir -p scripts/ho-latex
mkdir -p doc/latex/ho-latex
mkdir -p doc/latex/ho-latex/example
# mkdir -p doc/latex/ho-latex/test
mkdir -p source/latex/ho-latex
# mkdir -p source/latex/ho-latex/catalogue
#mkdir -p tex/generic/ho-latex
mkdir -p tex/latex/ho-latex


# unpack
#
tex ho-latex.ins

# make pdf
rm *.bbl || echo no bbl
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    #    biber ${i/.dtx}
    bibtex ${i/.dtx}
fi
echo lualatex ${i}
if [ -f ${i/.dtx/.idx} ]; then
    makeindex -s gind.ist ${i/.dtx/.idx}
echo     lualatex ${i}
fi
done

echo lualatex ho-latex
lualatex ho-latex


# special cases
rm -f ./tex/latex/ho-latex/foo.sty
# rm -f ./doc/latex/ho-latex/test/ifpdf-test1.tex
# rm -f ./source/latex/ho-latex/catalogue/ifpdf.xml

# fill tds tree
for i in `cat manifest.txt`
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../ho-latex.tds.zip
zip -r ../ho-latex.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm -f ho-latex.zip
zip ho-latex.zip ho-latex.tds.zip ho-latex/\
{README.txt,\
ho-latex.tex,\
*.pdf,\
*.dtx\
}

mv ho-latex*.zip ho-latex

