#!/bin/bash
set -e

# build ho-kv ctan distrib
# perhaps use l3build one day, but not today

INSTALLDIR=$HOME/texmf

# starting from ho-kv.zip and ho-kv.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex 2> /dev/null || echo target directories not present
rm *.pdf *.aux  2> /dev/null  || echo no pdf or aux here
mkdir -p $HOME/texmf/scripts/ho-kv


#  make target tds structure
mkdir -p bibtex/bib/ho-kv
mkdir -p scripts/ho-kv
mkdir -p doc/latex/ho-kv
mkdir -p doc/latex/ho-kv/example
# mkdir -p doc/latex/ho-kv/test
mkdir -p source/latex/ho-kv
# mkdir -p source/latex/ho-kv/catalogue
mkdir -p tex/generic/ho-kv
mkdir -p tex/latex/ho-kv


# unpack
#
tex ho-kv.ins

# make pdf
rm *.bbl || echo no bbl
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    #    biber ${i/.dtx}
    bibtex ${i/.dtx}
fi
lualatex ${i}
if [ -f ${i/.dtx/.idx} ]; then
    makeindex -s gind.ist ${i/.dtx/.idx}
    lualatex ${i}
fi
done

lualatex ho-kv
lualatex ho-kv


# special cases


# fill tds tree
for i in `cat manifest.txt`
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../ho-kv.tds.zip
zip -r ../ho-kv.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm -f ho-kv.zip
zip ho-kv.zip ho-kv.tds.zip ho-kv/\
{README.txt,\
ho-kv.tex,\
*.pdf,\
*.dtx\
}

mv ho-kv*.zip ho-kv

