#!/bin/bash
set -e

# build ho-if ctan distrib
# perhaps use l3build one day, but not today

INSTALLDIR=$HOME/texmf

# starting from ho-if.zip and ho-if.tds.zip from ctan


#
# cleanup
rm -r bibtex doc scripts source tex 2> /dev/null || echo target directories not present
rm *.pdf *.aux  2> /dev/null  || echo no pdf or aux here
mkdir -p $HOME/texmf/scripts/ho-if


#  make target tds structure
mkdir -p doc/generic/ho-if
mkdir -p source/generic/ho-if
mkdir -p tex/generic/ho-if


# unpack
#
tex ho-if.ins



# make pdf
rm *.bbl || echo no bbl
for i in *.dtx
do
lualatex ${i}
if [ -f ${i/.dtx/.bcf} ]; then
    #    biber ${i/.dtx}
    bibtex ${i/.dtx}
fi
lualatex ${i}
if [ -f ${i/.dtx/.idx} ]; then
    makeindex -s gind.ist ${i/.dtx/.idx}
    lualatex ${i}
fi
done

lualatex ho-if
lualatex ho-if


# special cases

# fill tds tree
for i in `cat manifest.txt`
do
    cp `basename $i` $i
done

echo making tds zip

rm -f ../ho-if.tds.zip
zip -r ../ho-if.tds.zip \
    bibtex doc scripts source tex

cd ..
echo making main zip
rm -f ho-if.zip
zip ho-if.zip ho-if.tds.zip ho-if/\
{README.txt,\
ho-if.tex,\
*.pdf,\
*.dtx\
}

mv ho-if*.zip ho-if

